/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    IconPicker: typeof import('./components/IconPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
